### ISSUE TITLE
Fullscreen Mode

### ISSUE THREAD

**Issue by Gismo567** [Avangelista/CarTube#10]
Is it possible to include a fullscreen mode like CarPlay enable that the sidebar of CarPlay is gone?

Thanks

**Comment by Avangelista** [comment]
This may be possible and will be done if it can be but is not a priority currently.

**Comment by Gismo567** [comment]
Thanks for the answer, would be nice if it works. Of course, first of all, everything has to run stable. Thank you for your hard work.

Von meinem iPhone gesendet
