### ISSUE TITLE
Code don't build

### ISSUE THREAD

**Issue by Thomas20090425** [Avangelista/CarTube#11]
<img width="2048" alt="截屏2023-01-11 下午9 21 07" src="https://user-images.githubusercontent.com/68798885/211960681-ddd9892b-f2d0-44e6-8e8e-c67ca3ff8138.png">

As title, any ideas?

Edit: sorry if I didnt give enough details, I've tried in Xcode, it also failed, I send this screen shot for debug purpose (because they are the exact same error), the only reason I'm building this but not using the provided iPA file is because I have a developer account and I wanted to try what if I put this app into TestFlight, and install it through there? that should make iOS trust this app to run on a car even with no Trollstore and on unsupported versions (BC its basically an iOS app with car play feature, right?).

Edit 2: No I'm not dumb trying to create a public TestFlight link, I'll install through private developer distribution, same thing. (I mean it would be cool if apple actually approved it if I applied 😏 )

So yes, any help is appreciated  @Avangelista

**Comment by Avangelista** [comment]
You will not be able to install this on a stock phone - TrollStore is required for certain entitlements not available to developers.
