### ISSUE TITLE
Video stops playing and stutters

### ISSUE THREAD

**Issue by shaneo88** [Avangelista/CarTube#16]
I can watch videos ok both on my wife’s car (2018 Hyundai i30) and my car (2009 Hyundai Getz w/ T’Eyes CC3 stereo), but on both cars and seemingly random times a video will seemingly pause, but keep playing audio as if it’s stuttering in the same spot. 

The only way I’ve found to fix the issue is close CarTube/unplug my phone and plug it in again. 

If I get a chance I’ll see if I can get it on video.

**Comment by Avangelista** [comment]
Give it a try with the latest version and see how you go! If it does stutter, try fullscreen -> exit -> pause -> play. Let me know how it goes!

**Comment by shaneo88** [comment]
Hey. 

Thanks for reaching out. I will try when I get home, but that won’t be for another week or so. 

Thanks,
Shane
