### ISSUE TITLE
iOS 16.3 without JB

### ISSUE THREAD

**Issue by dvavatsioulas** [Avangelista/CarTube#21]
Hello,
Will it ever be possible to install CarTube on a non-JB device, using Sideloadly for example, without Trollstore etc?
Just installing CarTube IPA on iOS 16+ devices, without JB. 
Do you believe you could make this work?
TIA!

**Comment by dvavatsioulas** [comment]
For reference, I tried just installing CarTube IPA via Sideloadly, app runs/opens on iPhone normally, but when I click "Play on CarPlay" nothing happens.

**Comment by Avangelista** [comment]
Unfortunately it is impossible. CarTube requires some entitlements that aren’t obtainable to ordinary devs and thus cannot be sideloaded normally.

**Comment by H859-gip** [comment]
Hi

**Comment by rihani** [comment]
I have installed this using AltStore but it isn't showing on my car. Any help

**Comment by Avangelista** [comment]
iOS 14-15.4.1 only. It cannot work with anything other than TrollStore.
