### ISSUE TITLE
Cant control volume

### ISSUE THREAD

**Issue by KAksonov** [Avangelista/CarTube#22]
2023 Camry Hybrid LE, Iphone SE 2020, ios 15.3.1

Cant control volume while app is active. Had to switch to Spotify and only after i start playing any song i can control volume. After that switch back to CarTube and press play again to continue watching video and cant control volume again. To be able to change it had to repeat everything from the beggining.

**Comment by Avangelista** [comment]
This appears to be an issue with the interaction between the app and your specific car. Unable to fix currently.
