### ISSUE TITLE
Unsure how to move forward

### ISSUE THREAD

**Issue by cfisher0** [Avangelista/CarTube#25]
New to GitHub I have no clue how to downloads or you never explained it told us how to do so

**Comment by MicrocontrollersDev** [comment]
> New to GitHub I have no clue how to downloads or you never explained it told us how to do so

If you’re on mobile, scroll to the bottom to find the releases page. If you’re on a computer, it’ll be on the right side of the screen. You can then see all the releases. Find the latest one (1.3 at the time of writing), and download the .ipa or .tipa from the assets dropdown at the bottom of the release (you may need to open the drop down to see the files). Then you can install the ipa through trollstore
