### ISSUE TITLE
No touch screen system

### ISSUE THREAD

**Issue by diegogarciaarriaza** [Avangelista/CarTube#29]
Allow me open this post for comment the problem with no touch screen systems.

The app works great but there are 3 negative points:
1. No direct navigation in cartube
2. No controls on video
3. No search option on app

I hope good news in the future

**Comment by Avangelista** [comment]
No plans for this currently. Perhaps in the future a lite version of this app will be released for those without touch screen systems.

**Comment by diegogarciaarriaza** [comment]
You break my heart
