### ISSUE TITLE
Cartube installed with scarlet

### ISSUE THREAD

**Issue by nicom86** [Avangelista/CarTube#30]
Hello I have installed cartube 1.3 with scarlet. It install fine looks like it will work but when i plug it into my wireless carplay the app does not appear on screen.
I have an 12 pro iphone running ios 16.3.

Can anyone Help me! Thanks for the app looks great.

**Comment by iuwz** [comment]
Same problem with iOS 16.2 iPhone 13 Pro 😢

**Comment by Avangelista** [comment]
Not supported above iOS 15.4.1.
