### ISSUE TITLE
suport ios

### ISSUE THREAD

**Issue by MSHARI-KHALD** [Avangelista/CarTube#38]
a car tube will support ios 16 because i really need this app

**Comment by dadokcz** [comment]
I install it to iOS 16 right now and i will try it in the few hours. I see that app missing in the CarPlay apps list so i think it will dont work.

**Comment by donghaedz** [comment]
> I install it to iOS 16 right now and i will try it in the car in the few hours. I see that app missing in the CarPlay apps list so i think it will dont work.

Have you tested on iOS 16 yet?
