### ISSUE TITLE
Video can't be played its likely the uploader disabled embedding 

### ISSUE THREAD

**Issue by Devilishx** [Avangelista/CarTube#4]
![9CDD1DF5-A7D8-46C9-929E-B5EA65897687](https://user-images.githubusercontent.com/46275004/211555512-1d3c8202-677d-4d00-8374-b8135cd5a395.jpeg)

Hi 
Most of youtube videos shows this error 
Im using trollstore  ios 15.3 iphone 13 pro max
thanks.

**Comment by st-ivan** [comment]
Hi, same issue here. I understand the ipa is just an interface which embeeds all youtube videos. Its not a native app like the one on Carbridge. Hope it can be fixable.

**Comment by Devilishx** [comment]
> 

i hope so :(

**Comment by Avangelista** [comment]
Fixed by adding referer to embed url requests
