### ISSUE TITLE
CarTube doesn’t show up

### ISSUE THREAD

**Issue by Eren82727** [Avangelista/CarTube#42]
When I plug the cable in my iPhone CarTube doesn’t show up. 
what is the problem i need help please

**Comment by Sup-ers** [comment]
Which firmware are you on?

**Comment by jydonmah** [comment]
Mine not showing on apple carplay for ios 16.5.1

**Comment by JAV4DH** [comment]
I have the same issue
My phone is iphone 11 ios 16
