### ISSUE TITLE
Blank screen on iOS16

### ISSUE THREAD

**Issue by L4Hacks** [Avangelista/CarTube#5]
Cartube has empty screen on the car app, on ios 16.

i’m jailbroken with palerain (iphone X).
Installed through trollStore.

“Play on CarPlay” button doesnt do anything.

Only thing working is the label asking to tap the phone when i lock the phone

**Comment by L4Hacks** [comment]
Yes i am, i just said it :)

**Comment by Avangelista** [comment]
iOS 16 is not planned to be supported at this stage
