### ISSUE TITLE
I can install CarTube to my iPhone 13 with iOS 16.6 but nothing happens on car play

### ISSUE THREAD

**Issue by brunoaduarte** [Avangelista/CarTube#52]
I can install CarTube to my iPhone 13 with iOS 16.6 using AltStore to sign it, but nothing happens on car play.

Is there anything else that has to be done for it to work ?

**Comment by davidsantin** [comment]
The same thing happens to me. I have signed it with a business certificate, the app opens without problems, but it does not appear in CarPlay.

**Comment by Avangelista** [comment]
As per the description, CarTube only supports iOS 14 - 15.4.1.
