### ISSUE TITLE
Screen freezes after using reverse camera

### ISSUE THREAD

**Issue by dinhchi27** [Avangelista/CarTube#8]
After using the reverse camera, the screen will freeze. Plz check and fix it.

**Comment by Avangelista** [comment]
When the screen freezes, does it resume the video if you press the CarPlay home button and then open the app again?

**Comment by dinhchi27** [comment]
> When the screen freezes, does it resume the video if you press the CarPlay home button and then open the app again?

No, I have to press the close button on the car screen. It will return to youtube homepage.

**Comment by Avangelista** [comment]
This should now work by opening and closing fullscreen, hopefully, with the latest version, but let me know how you go.
